name: PBGC Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
            
    - name: Install dependencies
      run: pip install -r config/requirements.txt

    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: python -m unittest discover -s tests

  build:
    needs: lint
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
  
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
  
    - name: Install dependencies
      run: pip install -r config/requirements.txt
  
    - name: Build Executable
      run: pyinstaller --onefile --name PBGC_Billing_Automation --add-data "config/sheet_template.xlsx;config/" --add-data "input;input" --add-data "output;output" --add-data "readMe.md;." main.py
   
    - name: Create Release Directory
      run: mkdir -p release
      shell: pwsh
    
    - name: Zip Dist Folder
      run: Compress-Archive -Path dist -DestinationPath release/dist.zip
      shell: pwsh

    - name: Upload Dist Zip as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pbgc-billing-automation-build
        path: release/dist.zip

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download Built Executable
      uses: actions/download-artifact@v3
      with:
        name: pbgc-billing-automation-build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/dist.zip
        tag_name: v1.0.1
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.PBGC_AUTO_GITHUB_TOKEN }}